### ISSUE TITLE
Annotation Page links to Container failure?

### ISSUE THREAD

**Issue by azaroth42** [BigBlueHat/web-annotation-protocol-tester#2]
```
  3) MUSTs 4.1.3 Responses with Annotations Page Response MUST have a link to the container that it is part of, using the partOf property:
     TypeError: Cannot read property 'body' of undefined
```

These seem like unrelated conditions?  `body` isn't needed for the link from the page to the container.

**Comment by BigBlueHat** [comment]
This is actually breaking because there's not a `res.body` (the JSON response content), not because there's not a `body` key in the JSON. :smile_cat: 

I'll fix it, so it throws an error if the body's empty.
